### ISSUE TITLE
how to get the 'x11' by homebrew

### ISSUE THREAD

**Issue by specter119** [agiliopadua/homebrew-extras#1]
I have modify your `xcrysden.rb` to match current homebrew. like change "x11" to `:x11`, but I found that you did the opposite way.

then how to get the 'x11' by homebrew?

I can build the package but get the error
```
/usr/local/Cellar/xcrysden/1.5.60/share/xcrysden-1.5.60/xcrysden: line 260: 46556 Segmentation fault: 11  ${XCRYSDEN_XCRYS_DIR}/xcrys ${XCRYSDEN_TOPDIR}/Tcl/xcInit.tcl $USE -- $XCRYSDEN_TOPDIR $XCRYSDEN_SCRATCH "$@" > /dev/null
```
each time starts.

**Comment by agiliopadua** [comment]
There’s a problem in recent mac os because of the old tcl/tk xcrysden requires and I don’t know how to fix it.

**Comment by specter119** [comment]
Thank @agiliopadua, I get it. I'm trying to find a solution.
